name: asassn-variability

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - astropy
  - matplotlib
  - seaborn
  - tqdm
  - ipython
  - ipykernel
  - jupyterlab
  - pip
  - pip:
      - celerite2

