name: malca

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - numba
  - astropy
  - matplotlib
  - seaborn
  - scikit-learn
  - joblib
  - pyarrow
  - duckdb
  - tqdm
  - ipython
  - ipykernel
  - jupyterlab
  - pip
  - pip:
      - celerite2
