[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "asassn-variability"
version = "0.1a0"
description = "ASAS-SN event analysis utilities"
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name = "Calder Lenhart" }]
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "tqdm",
    "matplotlib",
    "astropy",
    "celerite2",
    "pyarrow",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = [
    "baseline",
    "df_utils",
    "events_bayes",
    "filter",
    "lc_utils",
    "plot",
    "stats",
]
